#!/usr/bin/env node
/**
 * Phase 6.2b — Monthly Content Performance report.
 *
 * Schedule: 1st of the month. Source: Fathom (top pages, scroll depth) +
 * GSC (impressions/clicks by URL). Destination: Notion dashboard.
 */
import { sendTelegram, appendToNotion, requireEnv, pct } from "./_lib.mjs";

async function fetchFathomTopPages() {
  const apiKey = process.env.FATHOM_API_KEY;
  const siteId = process.env.FATHOM_SITE_ID;
  if (!apiKey || !siteId) return null;
  try {
    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    const until = new Date().toISOString().slice(0, 10);
    const res = await fetch(
      `https://api.usefathom.com/v1/aggregations?entity=pageview&entity_id=${siteId}&date_from=${since}&date_to=${until}&granularity=monthly&group_by=pathname`,
      { headers: { Authorization: `Bearer ${apiKey}` } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return (json ?? []).slice(0, 20).map((row) => ({
      path: row.pathname,
      views: row.pageviews ?? 0,
      avgTime: row.avg_duration ?? 0,
    }));
  } catch {
    return null;
  }
}

async function fetchGSCTopQueries() {
  // Stub — wire up when GSC service account is in place.
  return null;
}

async function main() {
  const missing = requireEnv([
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "NOTION_API_KEY",
    "NOTION_MONTHLY_CONTENT_DB_ID",
  ]);
  if (missing.length > 0) {
    console.log(`[skip] missing env: ${missing.join(", ")}`);
    process.exit(0);
  }

  const [topPages, topQueries] = await Promise.all([fetchFathomTopPages(), fetchGSCTopQueries()]);
  const generatedAt = new Date().toISOString();
  const monthLabel = generatedAt.slice(0, 7);

  const lines = [
    `# Monthly Content Performance — ${monthLabel}`,
    "",
    "## Top pages by views (Fathom, last 30d)",
    topPages && topPages.length > 0
      ? topPages.map((p, i) => `${i + 1}. \`${p.path}\` — ${p.views.toLocaleString()} views`).join("\n")
      : "_no data (FATHOM_API_KEY not configured)_",
    "",
    "## Top search queries (Google Search Console, last 30d)",
    topQueries && topQueries.length > 0
      ? topQueries.map((q, i) => `${i + 1}. "${q.query}" — ${q.clicks} clicks / ${q.impressions.toLocaleString()} impressions / ${pct(q.ctr)} CTR / pos ${q.position.toFixed(1)}`).join("\n")
      : "_no data (GSC not configured)_",
    "",
    "## Editorial takeaways",
    "- Double down on what ranks: articles appearing in the top 10 GSC queries should get internal links from the strongest pages.",
    "- Refresh the top 5 articles: titles, opening hook, and one new internal link each.",
    "- Identify any post losing traffic quarter-over-quarter and consider an update or a redirect.",
    "",
    "---",
    `_Generated by scripts/reports/monthly-content.mjs at ${generatedAt}._`,
  ];

  const markdown = lines.join("\n");
  const headline = `Monthly content report for ${monthLabel} is ready.`;

  const tg = await sendTelegram(`*${headline}*\n\n\`\`\`\n${markdown.slice(0, 3500)}\n\`\`\``);
  if (!tg.ok) console.error(`[warn] telegram: ${tg.error}`);

  const notion = await appendToNotion({
    parentDatabaseId: process.env.NOTION_MONTHLY_CONTENT_DB_ID,
    title: `Monthly Content Performance — ${monthLabel}`,
    body: markdown,
  });
  if (!notion.ok) console.error(`[warn] notion: ${notion.error}`);

  console.log(`[ok] monthly-content report generated`);
  console.log(`  telegram: ${tg.ok ? `message ${tg.messageId}` : `failed: ${tg.error}`}`);
  console.log(`  notion:   ${notion.ok ? `page ${notion.pageId}` : `failed: ${notion.error}`}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
