#!/usr/bin/env node
/**
 * Phase 6.2c — Weekly Revenue by Tier report.
 *
 * Schedule: Mondays. Source: Stripe (digital products, subscriptions) +
 * Shopify (physical product referrals via the rewritten /shop subdomain).
 * Destination: Notion dashboard + Telegram.
 *
 * "By tier" means the report breaks revenue down by price tier so Andre
 * can see whether the $47 guides, $497 programs, and $2500+ cohort offers
 * are each pulling their weight. Tier classification is heuristic: each
 * Stripe product is tagged with a metadata.tier field when the product is
 * created. Shopify orders don't have a tier, so they all bucket to
 * "referral" (the /shop -> shop.doseofproof.com redirect).
 */
import { sendTelegram, appendToNotion, requireEnv } from "./_lib.mjs";

async function fetchStripeWeekly() {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) return null;
  try {
    const since = Math.floor((Date.now() - 7 * 24 * 60 * 60 * 1000) / 1000);
    // List recent charges; in production use Charges API with expand=invoice.product
    // and Payment Intents for the full breakdown. This stub returns the contract.
    const res = await fetch(
      `https://api.stripe.com/v1/charges?created[gte]=${since}&limit=100`,
      { headers: { Authorization: `Bearer ${key}` } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return (json?.data ?? []).map((c) => ({
      amount: c.amount,
      productName: c.description ?? "(unknown)",
      tier: c.metadata?.tier ?? "untagged",
    }));
  } catch {
    return null;
  }
}

async function fetchShopifyWeekly() {
  const token = process.env.SHOPIFY_ADMIN_TOKEN;
  const shop = process.env.SHOPIFY_SHOP_DOMAIN;
  if (!token || !shop) return null;
  try {
    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
    const res = await fetch(
      `https://${shop}/admin/api/2024-04/orders.json?status=any&created_at_min=${since}&limit=250`,
      { headers: { "X-Shopify-Access-Token": token } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return (json?.orders ?? []).flatMap((o) =>
      (o.line_items ?? []).map((li) => ({
        amount: Math.round(parseFloat(li.price) * 100),
        productTitle: li.title,
        bucket: "referral",
      }))
    );
  } catch {
    return null;
  }
}

function groupByTier(rows) {
  const out = {};
  for (const r of rows) {
    if (!out[r.tier]) out[r.tier] = { count: 0, revenue: 0 };
    out[r.tier].count++;
    out[r.tier].revenue += r.amount;
  }
  return out;
}

async function main() {
  const missing = requireEnv([
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "NOTION_API_KEY",
    "NOTION_WEEKLY_REVENUE_DB_ID",
  ]);
  if (missing.length > 0) {
    console.log(`[skip] missing env: ${missing.join(", ")}`);
    process.exit(0);
  }

  const [stripe, shopify] = await Promise.all([fetchStripeWeekly(), fetchShopifyWeekly()]);
  const generatedAt = new Date().toISOString();

  const tiers = stripe ? groupByTier(stripe) : null;
  const stripeRevenue = stripe?.reduce((sum, r) => sum + r.amount, 0) ?? 0;
  const shopifyRevenue = shopify?.reduce((sum, r) => sum + r.amount, 0) ?? 0;
  const totalRevenue = stripeRevenue + shopifyRevenue;

  const lines = [
    `# Weekly Revenue — week of ${generatedAt.slice(0, 10)}`,
    "",
    `**Total:** $${(totalRevenue / 100).toFixed(2)}`,
    "",
    "## By tier (Stripe, digital products)",
    tiers
      ? Object.entries(tiers)
          .sort((a, b) => b[1].revenue - a[1].revenue)
          .map(([tier, agg]) => `- ${tier}: $${(agg.revenue / 100).toFixed(2)} (${agg.count} orders)`)
          .join("\n")
      : "_no data (STRIPE_SECRET_KEY not configured)_",
    "",
    "## By source",
    stripe ? `- Stripe (direct): $${(stripeRevenue / 100).toFixed(2)}` : "- Stripe: _no data_",
    shopify ? `- Shopify (referral): $${(shopifyRevenue / 100).toFixed(2)}` : "- Shopify: _no data_",
    "",
    "## Lead magnet attribution",
    "_Wire up: tag each Stripe checkout with metadata.utm_source to break down by lead magnet. Left as a follow-up because the lead-magnet pages don't currently pass UTM params through to the checkout link._",
    "",
    "---",
    `_Generated by scripts/reports/weekly-revenue.mjs at ${generatedAt}._`,
  ];

  const markdown = lines.join("\n");
  const headline = `Weekly revenue: $${(totalRevenue / 100).toFixed(2)} total.`;

  const tg = await sendTelegram(`*${headline}*\n\n\`\`\`\n${markdown.slice(0, 3500)}\n\`\`\``);
  if (!tg.ok) console.error(`[warn] telegram: ${tg.error}`);

  const notion = await appendToNotion({
    parentDatabaseId: process.env.NOTION_WEEKLY_REVENUE_DB_ID,
    title: `Weekly Revenue — ${generatedAt.slice(0, 10)}`,
    body: markdown,
  });
  if (!notion.ok) console.error(`[warn] notion: ${notion.error}`);

  console.log(`[ok] weekly-revenue report generated`);
  console.log(`  telegram: ${tg.ok ? `message ${tg.messageId}` : `failed: ${tg.error}`}`);
  console.log(`  notion:   ${notion.ok ? `page ${notion.pageId}` : `failed: ${notion.error}`}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
