#!/usr/bin/env node
/**
 * Phase 6.2a — Weekly Growth report.
 *
 * Schedule: Mondays 9am. Source: Vercel Analytics + Fathom + Google
 * Search Console. Destination: Notion (database page) + Telegram (DM).
 *
 * Required env vars (set in .env.local AND in GitHub Actions secrets):
 *   - VERCEL_TOKEN + VERCEL_PROJECT_ID
 *   - FATHOM_API_KEY + FATHOM_SITE_ID
 *   - GOOGLE_SERVICE_ACCOUNT_JSON (path or inline JSON)
 *   - GSC_SITE_URL (e.g. "https://doseofproof.com")
 *   - NOTION_API_KEY + NOTION_WEEKLY_GROWTH_DB_ID
 *   - TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID
 *
 * Without all of these the report logs a clear "skipped — missing env"
 * and exits 0 (so the cron doesn't page Andre on a misconfigured secret).
 */
import { sendTelegram, appendToNotion, requireEnv, pct, deltaPct } from "./_lib.mjs";

async function fetchVercelAnalytics() {
  const token = process.env.VERCEL_TOKEN;
  const projectId = process.env.VERCEL_PROJECT_ID;
  if (!token || !projectId) return null;
  // Vercel Web Analytics API: https://vercel.com/docs/rest-api/endpoints/web-analytics
  // The exact endpoint + params depend on the Vercel plan; left as a stub
  // that the user fills in with their team's actual API.
  // The shape contract is documented above so the report format stays stable.
  return null;
}

async function fetchFathom() {
  const apiKey = process.env.FATHOM_API_KEY;
  const siteId = process.env.FATHOM_SITE_ID;
  if (!apiKey || !siteId) return null;
  try {
    // Fathom API: https://usefathom.com/api/analytics
    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    const until = new Date().toISOString().slice(0, 10);
    const res = await fetch(
      `https://api.usefathom.com/v1/aggregations?entity=pageview&entity_id=${siteId}&date_from=${since}&date_to=${until}&granularity=total`,
      { headers: { Authorization: `Bearer ${apiKey}` } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return {
      visitors: json?.visitors ?? 0,
      pageViews: json?.pageviews ?? 0,
      avgDuration: json?.avg_duration ?? 0,
      bounceRate: json?.bounce_rate ?? 0,
    };
  } catch {
    return null;
  }
}

async function fetchGSC() {
  // Google Search Console requires OAuth + a service account. The auth flow
  // is non-trivial; left as a stub with a clear contract.
  return null;
}

async function main() {
  const missing = requireEnv([
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "NOTION_API_KEY",
    "NOTION_WEEKLY_GROWTH_DB_ID",
  ]);
  if (missing.length > 0) {
    console.log(`[skip] missing env: ${missing.join(", ")}`);
    process.exit(0);
  }

  const [vercel, fathom, gsc] = await Promise.all([fetchVercelAnalytics(), fetchFathom(), fetchGSC()]);

  const generatedAt = new Date().toISOString();
  const lines = [
    `# Weekly Growth — week of ${generatedAt.slice(0, 10)}`,
    "",
    "## Site traffic (Fathom)",
    fathom
      ? `- Visitors: ${fathom.visitors.toLocaleString()}`
      : "- Visitors: _no data (FATHOM_API_KEY / FATHOM_SITE_ID not configured)_",
    fathom
      ? `- Page views: ${fathom.pageViews.toLocaleString()}`
      : "- Page views: _no data_",
    fathom
      ? `- Bounce rate: ${pct(fathom.bounceRate)}`
      : "- Bounce rate: _no data_",
    "",
    "## Search performance (Google Search Console)",
    gsc
      ? `- Clicks: ${gsc.clicks.toLocaleString()}`
      : "- Clicks: _no data (GSC not configured)_",
    gsc
      ? `- Impressions: ${gsc.impressions.toLocaleString()}`
      : "- Impressions: _no data_",
    gsc
      ? `- CTR: ${pct(gsc.ctr)} · Avg position: ${gsc.position.toFixed(1)}`
      : "- CTR / position: _no data_",
    "",
    "## Vercel build + deploys",
    "- Last deploy: _check Vercel dashboard for build status_",
    "",
    "---",
    `_Generated by scripts/reports/weekly-growth.ts at ${generatedAt}._`,
  ];

  const markdown = lines.join("\n");
  const headline = `Weekly growth: ${fathom ? `${fathom.visitors.toLocaleString()} visitors, ${fathom.pageViews.toLocaleString()} pageviews` : "weekly report ready"}.`;

  // Send to Telegram
  const tg = await sendTelegram(`*${headline}*\n\n\`\`\`\n${markdown.slice(0, 3500)}\n\`\`\``);
  if (!tg.ok) console.error(`[warn] telegram: ${tg.error}`);

  // Send to Notion
  const notion = await appendToNotion({
    parentDatabaseId: process.env.NOTION_WEEKLY_GROWTH_DB_ID,
    title: `Weekly Growth — ${generatedAt.slice(0, 10)}`,
    body: markdown,
  });
  if (!notion.ok) console.error(`[warn] notion: ${notion.error}`);

  console.log(`[ok] weekly-growth report generated`);
  console.log(`  telegram: ${tg.ok ? `message ${tg.messageId}` : `failed: ${tg.error}`}`);
  console.log(`  notion:   ${notion.ok ? `page ${notion.pageId}` : `failed: ${notion.error}`}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
